SEED: &seed 1234

splitter:
  type: kfold # groupkfold, smlkf, stratifiedkfold
  nsplits: 5
  random_state: *seed
  labels: 
    - rule
    - rule_violation

classifier:
  model-name: "microsoft/deberta-v3-small"
  nepochs: 1
  learning-rate: 0.00002
  batch-size: 16
  gradient-accumulation-step: 1
  weight-decay: 0.01
  warmup-ratio: 0.1
  tokenizer:
    max-length: 2048
    truncation: true
    padding: 'longest'


